### ISSUE TITLE
Reorganize folder structure

### ISSUE THREAD

**Issue by dshgna** [rneha725/Online-Judge-for-LITG#1]
While there are no set guidelines for a project's folder structure, **separation of concerns** is generally a best practice. [Best Practices](http://stackoverflow.com/questions/24199004/best-practice-to-organize-javascript-library-css-folder-structure)

In the current setup, several JS and HTML files are mixed up. This makes navigation complicated. Something around this folder structure would be much better.

root 
    - home.html 
    - problems (all html for the problems)
    - css (all stylesheets)
    - js (all js files)
    - libs (all third party libraries)

**Some finer points**
1. Index.html is a better recognized for the root file than home.html. 
2. For now, directly include the 3rd party libraries via CDN. (Codepen handles most of this). Before deploying the app, we can use Bower to handle all 3rd party library dependencies. 
3. Bootstrap should be included unzipped :)

**Comment by rneha725** [comment]
I have changed the folder structure as suggested. Please refer to this commit message for folder structure: [commit](https://github.com/rneha725/Online-Judge-for-LITG/commit/dd4bc4e5120655cbf24375b72c70946495496524)
All points considered.

**Comment by dshgna** [comment]
Excellent work. This issue can be closed now.

Just a small point on commit messages. The usual naming convention is to write the heading as imperative, like you are commanding someone. For example 'Fix all changes in the Feb 17th issue". [More pointers here](https://github.com/erlang/otp/wiki/Writing-good-commit-messages). As this fix is basically a reorganization, a shorter commit message would be perfectly acceptable too.

**Comment by rneha725** [comment]
Thanks for suggestions, I will try to utilize all this in future.
